// Sistema de potenciadores para el clicker
export const upgrades = [
  // Multiplicadores básicos
  {
    id: "mate_basico",
    name: "Mate Básico",
    description: "Cada click vale x2",
    type: "multiplier",
    value: 1,
    cost: 20,
    unlockAt: 10,
  },
  {
    id: "termo_stanley",
    name: "Termo Stanley",
    description: "Cada click vale x3",
    type: "multiplier",
    value: 2,
    cost: 100,
    unlockAt: 50,
  },
  {
    id: "asado_dominguero",
    name: "Asado Dominguero",
    description: "Cada click vale x5",
    type: "multiplier",
    value: 4,
    cost: 500,
    unlockAt: 200,
  },
  {
    id: "camiseta_seleccion",
    name: "Camiseta de la Selección",
    description: "Cada click vale x10",
    type: "multiplier",
    value: 9,
    cost: 2000,
    unlockAt: 1000,
  },

  // Auto-clickers
  {
    id: "tio_del_asado",
    name: "Tío del Asado",
    description: "Genera 0.5 clicks por segundo",
    type: "autoclick",
    value: 0.5,
    cost: 50,
    unlockAt: 30,
  },
  {
    id: "taxista_opinologo",
    name: "Taxista Opinólogo",
    description: "Genera 1 click por segundo",
    type: "autoclick",
    value: 1,
    cost: 200,
    unlockAt: 100,
  },
  {
    id: "hincha_de_boca",
    name: "Hincha de Boca",
    description: "Genera 3 clicks por segundo",
    type: "autoclick",
    value: 3,
    cost: 800,
    unlockAt: 400,
  },
  {
    id: "diego_maradona",
    name: "Diego Maradona",
    description: "Genera 10 clicks por segundo",
    type: "autoclick",
    value: 10,
    cost: 5000,
    unlockAt: 2000,
  },
  {
    id: "lionel_messi",
    name: "Lionel Messi",
    description: "Genera 50 clicks por segundo",
    type: "autoclick",
    value: 50,
    cost: 20000,
    unlockAt: 10000,
  },
]
